code-review
MiMatyas/WeatherDatabase pull request #3
Opened 2023-12-14 21:18 UTC by MiMatyas

První CD

2023-12-15 19:48 UTC, jankoscak requested changes
Zapracujte prosim vsechny pripominky a pak bychom udelali merge tyhle vetve.

K tomu v samostatnej vetve prosim odstrante vsechny anotace @Service, @Component a namisto toho pouzijte @Bean a @Configuration.

V samostatne vetve udelejte z WeatherDataRetriever service, ktera ziska url a appid z konfigurace aplikace.

Pak bychom se se podivali na flyway/liquibase a testy.

K tomu vsemu jeste vsude doplnte javadoc a patricne anotace Nonnull/Nullable z jakarta.annotations.

2023-12-15 19:48 UTC, jankoscak commented on src/main/java/cz/matyas/WeatherDatabase/weather/WeatherDataRetriever.java
> +@Component
Mit tady tuhle anotaci je zbytecne, kdyz tahle trida ma jenom staticku metodu.

2023-12-15 19:48 UTC, jankoscak commented on src/main/java/cz/matyas/WeatherDatabase/weather/WeatherDataRetriever.java
> +    public static WeatherDataDTO getActualWeather(){
Udelame z tehle tridy servisu/klienta na komunikaci s externi sluzbou. Proto prosim vytvorte novou vetev, kde upravite tuhle metodu. Url api externi sluzby a appid by meli jit do konfigurace aplikace. Taky by tahle metoda mela reagovat na jinej navratovej kod ako 200. A aby sme z tyhle tridy udelali skutencou sluzbu, tak metoda bude prijimat ako parameter mesto, ktoreho pocasi chceme ziskat.

2023-12-15 19:48 UTC, jankoscak commented on src/main/java/cz/matyas/WeatherDatabase/weather/controller/WeatherController.java
> +    @Autowired
Ako sme se uz bavili na pohovoru, tak Autowire je tady zbytecne. Odmazte anotaci a vytvorte konstruktor, idealne pouzite patricnou lombok anotaci.

2023-12-15 19:48 UTC, jankoscak commented on src/main/java/cz/matyas/WeatherDatabase/weather/controller/WeatherController.java
> +    WeatherDataService weatherDataService;
Spravne by tady mel byt private, resp. private final, ak vyuzijete konstruktor na DI a ne anotaci Autowired.

2023-12-15 19:48 UTC, jankoscak commented on src/main/java/cz/matyas/WeatherDatabase/weather/dto/CloudsDTO.java
> +    }
Ty gettre a settre jsou zbytecne kdyz pouzivate Data anotaci. Plati to u vsech DTO.

2023-12-15 19:48 UTC, jankoscak commented on src/main/java/cz/matyas/WeatherDatabase/weather/entity/CloudsEntity.java
> +import jakarta.persistence.*;
Hvezdickove importy nepouzivat.

2023-12-15 19:48 UTC, jankoscak commented on src/main/java/cz/matyas/WeatherDatabase/weather/entity/CloudsEntity.java
> +    }
Tady by slo taky nahradit gettre settre pomoci lombok Setter/Getter annotace. Opet plati u vsech entit.

2023-12-16 23:42 UTC, MiMatyas commented on src/main/java/cz/matyas/WeatherDatabase/weather/dto/CloudsDTO.java
> +    }
Dotaz se vztahuje na všechna DTO.

U DTO předenou stojí výzva, když použiju anotaci @Data spolu s anotacemi @NonNull, lombok vytvoří v takovém DTO  
RequiredArgsConstructor.

Proto nemůžu zavolat metodu WeatherDataRetriever.getActualWeather(), protože ta používá pro získání dat z endpointu RestTemplate a ten je parsuje na DTO objekt pomocí bezparametrického konstruktoru daného DTO(DTO ale bezparametricky konstruktor nemá) 

potřebuji se zeptat, jak mám situaci řešit, jestli mám situaci řešit přidáním bezparametrického konstruktoru do DTO, nebo jestli mám json parsovat do DTO pomocí parametrického konstruktoru (podle způsobu který sem si našel by to obnášelo použít knihovnu Jackson)
popřípadě jestli mám vymyslet ještě nějaký jiný způsob jak to vyřešit.
Nerad bych si aplikaci rozbil tím že bych to ignoroval.

2023-12-17 22:23 UTC, MiMatyas commented on src/main/java/cz/matyas/WeatherDatabase/weather/WeatherDataRetriever.java
> +@Component
anotace odstraněna

2023-12-17 22:26 UTC, MiMatyas commented on src/main/java/cz/matyas/WeatherDatabase/weather/controller/WeatherController.java
> +    @Autowired
Autowired jsem odstranil a nahradil konstruktorem na DI, výslovně jste to nepožadoval, ale nahradil jsem Autowired za konstruktor s DI na všech místech kódu, to je ve všech servisách a v  WeatherTask

2023-12-17 22:27 UTC, MiMatyas commented on src/main/java/cz/matyas/WeatherDatabase/weather/controller/WeatherController.java
> +    WeatherDataService weatherDataService;
Autowired jsem odstranil a nahradil konstruktorem na DI

2023-12-17 22:28 UTC, MiMatyas commented on src/main/java/cz/matyas/WeatherDatabase/weather/dto/CloudsDTO.java
> +    }
gettery a settery jsem odstranil

2023-12-17 22:28 UTC, MiMatyas commented on src/main/java/cz/matyas/WeatherDatabase/weather/entity/CloudsEntity.java
> +import jakarta.persistence.*;
hvezdičkove importy jsem odstranil ze všech tříd

2023-12-17 22:29 UTC, MiMatyas commented on src/main/java/cz/matyas/WeatherDatabase/weather/entity/CloudsEntity.java
> +    }
gettery a settery jsem nahradil anotacemi Setter/Getter

2023-12-17 22:32 UTC, MiMatyas commented
Do všech tříd jsem přidal javadoc a Nullable/NonNull, 2 větve které si mám vytvořit a udělat v nich patřičné úpravy si budu vytvářet z aktuálního komitu tj.: "f389047" abych v nich měl zahrnuté změny, které jsem do teď udělal.

2023-12-17 22:38 UTC, MiMatyas commented
všechny změny jsem rozdělil do jednotlivých commitů aby byly přehledné

2023-12-18 12:11 UTC, jankoscak commented
> všechny změny jsem rozdělil do jednotlivých commitů aby byly přehledné

Neni nutne kazdou drobnost commitovat zvlast, spis commitovat logicke celky. Pridani javadocu do cele aplikace commit, pridani anotaci Nonnull/Nullable commit atd. 

Kedze delame pull request z master do code-review vetvy, tak vsechny zmeny delate v master a kdyz vytvorite vetev z master, tak je mate vzdy vsechny. 

Jeste ste nezapracoval odstraneni `Component`, `Service` anotaci a pouziti `Configuration` a `Bean` anotace. To udelejte v samostatne vetve, ktera bude vychazet z master. 

Tohle povazuji za hotove.

2023-12-18 12:11 UTC, merged